import * as utils from "./src/utils";

export default utils;
export const merge = utils.merge;
export const delay = utils.delay;
export const isTypedArray = utils.isTypedArray;
export const toArray = utils.toArray;
export const endsWith = utils.endsWith;
export const toFlatObject = utils.toFlatObject;
export const inherits = utils.inherits;
export const stripBOM = utils.stripBOM;
export const extend = utils.extend;
export const forEach = utils.forEach;
export const isStandardBrowserEnv = utils.isStandardBrowserEnv;
export const trim = utils.trim;
export const isURLSearchParams = utils.isURLSearchParams;
export const isFormData = utils.isFormData;
export const isStream = utils.isStream;
export const isFunction = utils.isFunction;
export const isFileList = utils.isFileList;
export const isBlob = utils.isBlob;
export const isFile = utils.isFile;
export const isDate = utils.isDate;
export const isPlainObject = utils.isPlainObject;
export const isObject = utils.isObject;
export const isNumber = utils.isNumber;
export const isString = utils.isString;
export const isArrayBufferView = utils.isArrayBufferView;
export const isArrayBuffer = utils.isArrayBuffer;
export const isBuffer = utils.isBuffer;
export const isUndefined = utils.isUndefined;
export const isArray = utils.isArray;